In [8]:
import numpy as np

In [11]:
# When we pass a homogenous list in numpy array it converts it into array.
l = [1,2,3,4,5,6]

In [12]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [18]:
# When we pass heterogenous list to numpy array it converts all the elements of array to higher order in this case it has converted it to string.
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [27]:
a1 = np.array(l1)

In [28]:
# Here all the elements of array is converted to Higher order i.e string in this case.<u32> is an internal representation of a data type for numpy array.
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [29]:
# list inside list--> It gives a 2-d array.
a2 = np.array([[1,2,3] , [4,5,6]])

In [30]:
# Since there are 3 [] hence it is 3d array
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [31]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
#ndim tells us about the dimension of array.
a1.ndim

1

In [35]:
a2.ndim

2

In [36]:
a3.ndim

3

In [42]:
# size tells about the total no. of elements in an array.
a1.size

7

In [38]:
a2.size

6

In [39]:
a3.size

9

In [41]:
# since a1 is 1-d array hence there is only one row there hence it is giving 7.
a1.shape

(7,)

In [45]:
# It saya a2 has a shape of 2*3
a2.shape

(2, 3)

In [44]:
# we have 3*3 of 1 such matrix
a3.shape

(1, 3, 3)

In [48]:
# It generates the data of specific dimension here it is 3*4.
np.random.randint(2,50 ,(3,4) )

array([[ 7, 20, 26, 31],
       [39,  3, 19, 11],
       [37, 40, 21, 20]])

In [51]:
# Here it generates a 3-d data. We have 2 matrix of 3*4.
np.random.randint(2,50 ,(2,3,4) )

array([[[29, 30, 42, 13],
        [ 8, 16, 24, 40],
        [21, 24, 42,  9]],

       [[ 2, 24, 21, 41],
        [49, 13, 27, 42],
        [40, 26, 34,  2]]])

In [58]:
# rand()--> It generates random nos of 5*4 matrix.
np.random.rand(5,4)

array([[0.38205027, 0.2431825 , 0.51384527, 0.77924503],
       [0.54223857, 0.62364535, 0.27120193, 0.38769755],
       [0.21180001, 0.25454921, 0.18325979, 0.45558903],
       [0.95114197, 0.42450369, 0.00211033, 0.78393322],
       [0.51524885, 0.21796228, 0.98608846, 0.54342832]])

In [60]:
# randn()-->It generates normally distributed dataset.A data set which has mean = 0 and S.D = 1 is called normally distributed data.
# Here takes any row or column and take the mean of it. It will tends towards 0. i.e approx 0.
a4 = np.random.randn(4,4)

In [61]:
a4

array([[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894],
       [-1.27659704, -0.01056311,  0.37607191,  0.12487388],
       [-0.87434511, -0.01753503, -1.71766143,  0.54404313],
       [-0.72343976, -1.81312085, -1.22800248,  1.38052251]])

In [66]:
# here 2*8 = 16 hence it can reshape the a4 data. Different permutation combination for 16 is (1,16), (16,1), (2,8),(8,2) and (4,4)
a4.reshape(2,8)

array([[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894, -1.27659704,
        -0.01056311,  0.37607191,  0.12487388],
       [-0.87434511, -0.01753503, -1.71766143,  0.54404313, -0.72343976,
        -1.81312085, -1.22800248,  1.38052251]])

In [67]:
# it gives error bcz a4 holds in total 4*4 = 16 data. So we need to reshape it with the same no. od data.
# Here 3*4 = 12 < 16 hence it gives error
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [65]:
a4.reshape(1,16)

array([[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894, -1.27659704,
        -0.01056311,  0.37607191,  0.12487388, -0.87434511, -0.01753503,
        -1.71766143,  0.54404313, -0.72343976, -1.81312085, -1.22800248,
         1.38052251]])

In [74]:
# Whenever you give a -ve no. it takes the choose the second no. automatically. which is 8 in this case.
# It is similar to crop.
a4.reshape(2,-1)

array([[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894, -1.27659704,
        -0.01056311,  0.37607191,  0.12487388],
       [-0.87434511, -0.01753503, -1.71766143,  0.54404313, -0.72343976,
        -1.81312085, -1.22800248,  1.38052251]])

In [71]:
# Any negative no. does the same. Here it Choose the 2nd no. as 8. since 2*8 = 16
a4.reshape(2,-134564364)

array([[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894, -1.27659704,
        -0.01056311,  0.37607191,  0.12487388],
       [-0.87434511, -0.01753503, -1.71766143,  0.54404313, -0.72343976,
        -1.81312085, -1.22800248,  1.38052251]])

In [75]:
# Same way we can reshape it into 3-d array.
a4.reshape(2,2,4)

array([[[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894],
        [-1.27659704, -0.01056311,  0.37607191,  0.12487388]],

       [[-0.87434511, -0.01753503, -1.71766143,  0.54404313],
        [-0.72343976, -1.81312085, -1.22800248,  1.38052251]]])

In [78]:
# same way we can reshape it into any dimension array but it's total no. of element should be 16.
a4.reshape(1,1,1,1,1,1,2,2,4)

array([[[[[[[[[ 0.54572108, -0.28293474, -0.0046588 , -0.40066894],
              [-1.27659704, -0.01056311,  0.37607191,  0.12487388]],

             [[-0.87434511, -0.01753503, -1.71766143,  0.54404313],
              [-0.72343976, -1.81312085, -1.22800248,  1.38052251]]]]]]]]])

In [79]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [80]:
a1[0]

'4'

# Slicing operation on Array.
It is same as list

In [82]:
# It will consider the index from 2 to 5. i.e upper index-1
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

From 1 to 5 with a jump of 2

In [86]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

Reverse of Array

In [85]:

a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [88]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [89]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

# Different ways to get only 2,3,5,6 out of a2 using slicing operation?

In [91]:
# 1. 
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [93]:
# 2.
a2[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [95]:
# 3
a2[:, [1,2] ]

array([[2, 3],
       [5, 6]])

In [96]:
# 4
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

# Create 6*5 mtrix whose values should be in between 2 to 89

In [98]:
a5 = np.random.randint(2,90 , (6,5))

In [99]:
a5

array([[51, 68, 15, 51,  5],
       [88, 43, 77, 47, 80],
       [68, 47, 50,  2, 72],
       [60, 45, 35, 10, 84],
       [10, 19, 12, 53, 87],
       [ 5,  9, 88, 54, 59]])

 find all the nos. in a5 which is grater than 50

In [100]:
a5[a5 > 40]

array([51, 68, 51, 88, 43, 77, 47, 80, 68, 47, 50, 72, 60, 45, 84, 53, 87,
       88, 54, 59])

Change the (0,1) element of a5 to 100

In [101]:
a5[0,1] = 100

In [102]:
a5

array([[ 51, 100,  15,  51,   5],
       [ 88,  43,  77,  47,  80],
       [ 68,  47,  50,   2,  72],
       [ 60,  45,  35,  10,  84],
       [ 10,  19,  12,  53,  87],
       [  5,   9,  88,  54,  59]])

# Matrix Multiplication
Criteria to perform matrix multiplication is (column of first matrix = row of 2nd matrix)
Eg:- If first matrix of shape (n*m)
2nd matrix of shape (p*q)
Then Matrix multiplication is only possible iff (m==q)
and the reulting matrix will be of size (n*q)

In [103]:
a6 = np.random.randint(0,3 , (3,3))

In [104]:
a7 = np.random.randint(0,3 , (3,3))

In [105]:
a6

array([[1, 2, 0],
       [2, 1, 1],
       [0, 1, 0]])

In [106]:
a7

array([[2, 0, 1],
       [0, 0, 1],
       [2, 0, 1]])

In [108]:
# This is not actual matrix multiplication. It is element wise multiplication.
a6*a7

array([[2, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [115]:
# By using @ symbol we perform the actual matrix multiplication. 
a6@a7

array([[2, 0, 3],
       [6, 0, 4],
       [0, 0, 1]])

In [111]:
a6

array([[1, 2, 0],
       [2, 1, 1],
       [0, 1, 0]])

In [113]:
# It will add 100 in each element of a6.
a6+100

array([[101, 102, 100],
       [102, 101, 101],
       [100, 101, 100]])

In [114]:

a6*2

array([[2, 4, 0],
       [4, 2, 2],
       [0, 2, 0]])

In [117]:
# in numpy divide by 0 doesn't give error. It just give the warning and gives the result matrix.
a6/0

/var/folders/y4/6_3sgdc945dcscpnt6p8q7100000gn/T/ipykernel_3475/914220672.py:2: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
/var/folders/y4/6_3sgdc945dcscpnt6p8q7100000gn/T/ipykernel_3475/914220672.py:2: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [inf, inf, inf],
       [nan, inf, nan]])

In [119]:
a6

array([[1, 2, 0],
       [2, 1, 1],
       [0, 1, 0]])

In [120]:
# power of 3
a6**3

array([[1, 8, 0],
       [8, 1, 1],
       [0, 1, 0]])

In [122]:
# zeros()--> This function gives the 0 matrix of the size given.
a8 = np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
a9  = np.ones((4,5))

In [124]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [125]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

# Broadcasting operation
To every row it broadcast the element

In [129]:
# Row wise it adds to the particular list
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [130]:
# Here it gives error bcz (list element < no. of columns in a9)
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [131]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [152]:
# First Do the transpose of a 2-d matrix and then add to a9. After transpose (no. of rows in matrix given = no. of rows in a9).
#Here it will do the broadcasting operation column wise.
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [135]:
# Transpose of a matrx
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [136]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [138]:
a6

array([[1, 2, 0],
       [2, 1, 1],
       [0, 1, 0]])

In [139]:
# In this case a6 = a6.T
a6.T

array([[1, 2, 0],
       [2, 1, 1],
       [0, 1, 0]])

In [141]:
a5

array([[ 51, 100,  15,  51,   5],
       [ 88,  43,  77,  47,  80],
       [ 68,  47,  50,   2,  72],
       [ 60,  45,  35,  10,  84],
       [ 10,  19,  12,  53,  87],
       [  5,   9,  88,  54,  59]])

In [143]:
# Square root of each element of a5
np.sqrt(a5)

array([[ 7.14142843, 10.        ,  3.87298335,  7.14142843,  2.23606798],
       [ 9.38083152,  6.55743852,  8.77496439,  6.8556546 ,  8.94427191],
       [ 8.24621125,  6.8556546 ,  7.07106781,  1.41421356,  8.48528137],
       [ 7.74596669,  6.70820393,  5.91607978,  3.16227766,  9.16515139],
       [ 3.16227766,  4.35889894,  3.46410162,  7.28010989,  9.32737905],
       [ 2.23606798,  3.        ,  9.38083152,  7.34846923,  7.68114575]])

In [154]:
# exponent of each element a5
np.exp(a5)

array([[1.40934908e+22, 2.68811714e+43, 3.26901737e+06, 1.40934908e+22,
        1.48413159e+02],
       [1.65163625e+38, 4.72783947e+18, 2.75851345e+33, 2.58131289e+20,
        5.54062238e+34],
       [3.40427605e+29, 2.58131289e+20, 5.18470553e+21, 7.38905610e+00,
        1.85867175e+31],
       [1.14200739e+26, 3.49342711e+19, 1.58601345e+15, 2.20264658e+04,
        3.02507732e+36],
       [2.20264658e+04, 1.78482301e+08, 1.62754791e+05, 1.04137594e+23,
        6.07603023e+37],
       [1.48413159e+02, 8.10308393e+03, 1.65163625e+38, 2.83075330e+23,
        4.20121040e+25]])

In [146]:
# log of each element of a5
np.log10(a5)

array([[1.70757018, 2.        , 1.17609126, 1.70757018, 0.69897   ],
       [1.94448267, 1.63346846, 1.88649073, 1.67209786, 1.90308999],
       [1.83250891, 1.67209786, 1.69897   , 0.30103   , 1.8573325 ],
       [1.77815125, 1.65321251, 1.54406804, 1.        , 1.92427929],
       [1.        , 1.2787536 , 1.07918125, 1.72427587, 1.93951925],
       [0.69897   , 0.95424251, 1.94448267, 1.73239376, 1.77085201]])

# Difference between range() and arange()

# range()

In [162]:
# It will make a list of elec=ment from 0 to 9 with a jump of 2.
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [157]:
# floating point no. is not accaptable in range(). Hence in numpy we have a function called arange().
list(range(0,10 , 2.5))

TypeError: 'float' object cannot be interpreted as an integer

# arange()

In [168]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [171]:
# arange() function in numpy accepts floating point nos.
# Make a list of data from 1.8 to 10.7 with a jump of 2.5
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

# Difference between linespace() and logspace()

# linespace():- This function is used to generate nos. between the given range in an array.

In between 2 and 3 generate 50 nos with stepsize.

In [149]:
# linespace()-->  where retstep= True gives the value of step size at last.
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

# logspace()

In [170]:
# logspace and linespace is almost same only difference is linspace considers linear space whereas logsapce considers logarithmic space.
np.logspace(2,4,num=4 , base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

# eye():--> Used to generate the identity matrix.
Identity Matrix:- it should be of n*n i.e (no. of rows= no. of columns) All the digonal elements shold be 1 and all non diagonal elements shoulfd be 0. and the determinant of matrix should be 1.

In [173]:
# It gives the identity matrix of 5*5.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Data Visualization
libraries:- matplotlib, cufflinks, seaborn, plotly

In [174]:
import cufflinks as cf 

ModuleNotFoundError: No module named 'cufflinks'

# Install Cufflink

In [179]:
!pip install cufflinks

In [182]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns
# seaborn is bydefault installed with anaconda


In [184]:
# In offline mode we are going to do everything
cf.go_offline()

# Create a data frame having 100 rows and 3 columns A, B, C.

In [204]:

df = pd.DataFrame(np.random.randn(100,3), columns=['A', 'B', 'C'])

In [205]:
df

A         B         C
0  -0.688614 -1.434940  0.098707
1  -0.930975 -0.602229  0.266169
2   3.265323 -0.966453  1.185206
3   0.439814  0.548074  0.102833
4  -0.527756  0.073500  0.285581
..       ...       ...       ...
95 -1.442238 -0.695524 -1.526569
96 -1.226147 -0.634132 -0.220030
97 -1.222960  0.984912  0.869839
98 -0.559777  0.046050 -0.160084
99 -1.057388 -0.049939 -0.121306

[100 rows x 3 columns]

# fluctuation of data can be seen using a function called iplot()

In [214]:
# x axis represents the row value and y axis represents the actual value.
df.iplot()

# Create a df of 100*1 having elements between 3 to 100

In [208]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [209]:
df1

0
0   38
1    8
2   42
3   67
4   99
..  ..
95  83
96  70
97  94
98  44
99  95

[100 rows x 1 columns]

In [213]:
# By using iplot function we can tell the fluctuation of data in  a particular range.
# The library which we are using here is cufflinks you can say.
df1.iplot()

In [215]:

df

A         B         C
0  -0.688614 -1.434940  0.098707
1  -0.930975 -0.602229  0.266169
2   3.265323 -0.966453  1.185206
3   0.439814  0.548074  0.102833
4  -0.527756  0.073500  0.285581
..       ...       ...       ...
95 -1.442238 -0.695524 -1.526569
96 -1.226147 -0.634132 -0.220030
97 -1.222960  0.984912  0.869839
98 -0.559777  0.046050 -0.160084
99 -1.057388 -0.049939 -0.121306

[100 rows x 3 columns]

In [218]:
# How A is moving w.r.t B?
# mode = 'markers' will change the graph from line to dotted one.
df.iplot(x = 'A' , y = 'B', mode = 'markers')

In [224]:
# titanic dataset is available everywhere on github and other places so we can access it directly
df2 = sns.load_dataset('titanic')

In [225]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [228]:
# Relationship between age and fare.
# There is no relation between age and fare
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [230]:
# Relation between age and pclass i.e passanger class.
# Data is eqally distributed for all the 3 class for all different ages.
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [231]:
# Relation between fare and pclass
# pclass is inversly propotional to fare pclass 3 has less fare than pclass 1.
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [232]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

# From the above titanic dataset find out wheter male was more or female was more?

In [234]:
# who has survived more whether male or female?
# kind = bar means we are trying to plot bar graph
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')